# bSMOTE

## Borderline-1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()
df

AD_MCP    AD_PCT    AD_GCC    AD_BCC    AD_SCC     AD_FX  AD_CST_R  \
0    0.001177  0.000974  0.001479  0.001474  0.001575  0.002257  0.001079   
2    0.001213  0.001075  0.001567  0.001585  0.001686  0.002492  0.001046   
3    0.001101  0.000965  0.001440  0.001433  0.001456  0.002379  0.000985   
4    0.001053  0.000904  0.001433  0.001470  0.001450  0.002421  0.000966   
5    0.001131  0.000974  0.001469  0.001498  0.001531  0.002291  0.000994   
..        ...       ...       ...       ...       ...       ...       ...   
963  0.001117  0.001011  0.001574  0.001646  0.001712  0.002214  0.001094   
964  0.001181  0.001002  0.001423  0.001505  0.001530  0.002266  0.001088   
965  0.001126  0.000949  0.001542  0.001747  0.001642  0.002565  0.000978   
966  0.001090  0.000976  0.001354  0.001421  0.001427  0.001928  0.001018   
967  0.001097  0.000984  0.001477  0.001419  0.001502  0.002556  0.001063   

     AD_CST_L   AD_ML_R   AD_ML_L  ...   RD_FXST    RD_SLF    RD_SFO  \
0    0.001081  0.001285  0.001287  ...  0.000662  0.000577  0.000551   
2    0.001056  0.001149  0.001126  ...  0.000769  0.000694  0.000902   
3    0.000990  0.001118  0.001113  ...  0.000614  0.000546  0.000562   
4    0.000977  0.001047  0.001041  ...  0.000607  0.000535  0.000551   
5    0.001017  0.001128  0.001105  ...  0.000621  0.000559  0.000586   
..        ...       ...       ...  ...       ...       ...       ...   
963  0.001118  0.001228  0.001248  ...  0.000734  0.000647  0.000913   
964  0.001103  0.001224  0.001203  ...  0.000584  0.000593  0.000624   
965  0.001052  0.001162  0.001190  ...  0.000577  0.000589  0.000835   
966  0.001007  0.001241  0.001188  ...  0.000560  0.000517  0.000514   
967  0.001147  0.001268  0.001199  ...  0.000601  0.000537  0.000766   

       RD_UNC    RD_TAP     RD_IC     RD_CC     RD_CR  RD_FULLWM  \
0    0.000600  0.001139  0.000491  0.000562  0.000638   0.000571   
2    0.000717  0.001507  0.000626  0.000701  0.000851   0.000723   
3    0.000553  0.000950  0.000448  0.000512  0.000587   0.000531   
4    0.000530  0.000862  0.000437  0.000509  0.000573   0.000522   
5    0.000558  0.000901  0.000458  0.000527  0.000605   0.000545   
..        ...       ...       ...       ...       ...        ...   
963  0.000599  0.001623  0.000538  0.000680  0.000744   0.000652   
964  0.000619  0.000878  0.000487  0.000567  0.000618   0.000571   
965  0.000534  0.001478  0.000440  0.000694  0.000659   0.000597   
966  0.000566  0.000729  0.000441  0.000469  0.000534   0.000509   
967  0.000605  0.001115  0.000446  0.000598  0.000608   0.000556   

     Research Group  
0                CN  
2                CN  
3                CN  
4                CN  
5                CN  
..              ...  
963              AD  
964              CN  
965              AD  
966              CN  
967             MCI  

[933 rows x 293 columns]

In [2]:
from imblearn.over_sampling import BorderlineSMOTE as bSMOTE
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = bSMOTE(kind='borderline-1').fit_resample(X, y)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=8)

In [4]:
from sklearn.naive_bayes import GaussianNB

# Build a Gaussian Classifier
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: SMC


In [5]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
)

y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.36205128205128206
F1 Score: 0.4000810627247669


In [6]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[102,   4,   0,   6,   2,  36],
       [ 23,  41,  24,  13,   7,  52],
       [ 50,  24,  25,  10,   0,  48],
       [ 31,  10,   0,  42,   6,  78],
       [ 29,  22,  16,  11,  18,  75],
       [ 10,   4,  10,  17,   4, 125]])

### Combined MCI groups

In [7]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()
df

AD_MCP    AD_PCT    AD_GCC    AD_BCC    AD_SCC     AD_FX  AD_CST_R  \
0    0.001177  0.000974  0.001479  0.001474  0.001575  0.002257  0.001079   
2    0.001213  0.001075  0.001567  0.001585  0.001686  0.002492  0.001046   
3    0.001101  0.000965  0.001440  0.001433  0.001456  0.002379  0.000985   
4    0.001053  0.000904  0.001433  0.001470  0.001450  0.002421  0.000966   
5    0.001131  0.000974  0.001469  0.001498  0.001531  0.002291  0.000994   
..        ...       ...       ...       ...       ...       ...       ...   
963  0.001117  0.001011  0.001574  0.001646  0.001712  0.002214  0.001094   
964  0.001181  0.001002  0.001423  0.001505  0.001530  0.002266  0.001088   
965  0.001126  0.000949  0.001542  0.001747  0.001642  0.002565  0.000978   
966  0.001090  0.000976  0.001354  0.001421  0.001427  0.001928  0.001018   
967  0.001097  0.000984  0.001477  0.001419  0.001502  0.002556  0.001063   

     AD_CST_L   AD_ML_R   AD_ML_L  ...   RD_FXST    RD_SLF    RD_SFO  \
0    0.001081  0.001285  0.001287  ...  0.000662  0.000577  0.000551   
2    0.001056  0.001149  0.001126  ...  0.000769  0.000694  0.000902   
3    0.000990  0.001118  0.001113  ...  0.000614  0.000546  0.000562   
4    0.000977  0.001047  0.001041  ...  0.000607  0.000535  0.000551   
5    0.001017  0.001128  0.001105  ...  0.000621  0.000559  0.000586   
..        ...       ...       ...  ...       ...       ...       ...   
963  0.001118  0.001228  0.001248  ...  0.000734  0.000647  0.000913   
964  0.001103  0.001224  0.001203  ...  0.000584  0.000593  0.000624   
965  0.001052  0.001162  0.001190  ...  0.000577  0.000589  0.000835   
966  0.001007  0.001241  0.001188  ...  0.000560  0.000517  0.000514   
967  0.001147  0.001268  0.001199  ...  0.000601  0.000537  0.000766   

       RD_UNC    RD_TAP     RD_IC     RD_CC     RD_CR  RD_FULLWM  \
0    0.000600  0.001139  0.000491  0.000562  0.000638   0.000571   
2    0.000717  0.001507  0.000626  0.000701  0.000851   0.000723   
3    0.000553  0.000950  0.000448  0.000512  0.000587   0.000531   
4    0.000530  0.000862  0.000437  0.000509  0.000573   0.000522   
5    0.000558  0.000901  0.000458  0.000527  0.000605   0.000545   
..        ...       ...       ...       ...       ...        ...   
963  0.000599  0.001623  0.000538  0.000680  0.000744   0.000652   
964  0.000619  0.000878  0.000487  0.000567  0.000618   0.000571   
965  0.000534  0.001478  0.000440  0.000694  0.000659   0.000597   
966  0.000566  0.000729  0.000441  0.000469  0.000534   0.000509   
967  0.000605  0.001115  0.000446  0.000598  0.000608   0.000556   

     Research Group  
0                CN  
2                CN  
3                CN  
4                CN  
5                CN  
..              ...  
963              AD  
964              CN  
965              AD  
966              CN  
967             MCI  

[933 rows x 293 columns]

In [8]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = bSMOTE(kind='borderline-1').fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=8)

In [9]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: AD


In [10]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.5610200364298725
F1 Score: 0.6000493907478462


In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[162,  31,   2],
       [ 32, 116,  30],
       [ 48,  98,  30]])

## Borderline-2

In [12]:
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [13]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = bSMOTE(kind='borderline-2').fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=10)

In [14]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: EMCI


In [15]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.3726899383983573
F1 Score: 0.4061864361995949


In [16]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[108,   9,  11,  18,   1,  32],
       [ 19,  41,  25,  23,   7,  43],
       [ 29,  31,  35,  17,   0,  48],
       [ 32,  20,   5,  69,   2,  32],
       [ 29,  26,  22,  39,   9,  35],
       [ 18,  11,  12,  14,   1, 101]])

### Combined MCI groups

In [17]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [18]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = bSMOTE(kind='borderline-2').fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=10)

In [19]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: AD


In [20]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.5218978102189781
F1 Score: 0.5504666143027055


In [21]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[148,  29,   7],
       [ 42,  96,  40],
       [ 65,  79,  42]])

## bSMOTE with SVM

In [22]:
from imblearn.over_sampling import SVMSMOTE
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [23]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = SVMSMOTE().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=22)

In [24]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: LMCI


In [25]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.38591549295774646
F1 Score: 0.40004968944974656


In [26]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[73,  0,  3, 14,  1, 10],
       [21, 22, 19, 19, 28, 50],
       [42,  4, 44,  9, 17, 27],
       [12,  5,  3, 28,  4, 17],
       [19,  8, 14, 22, 63, 43],
       [ 6,  1,  4,  9,  5, 44]])

### Combined MCI groups

In [27]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [28]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = SVMSMOTE().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=32)

In [29]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: CN


In [30]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.5046511627906977
F1 Score: 0.5302964477383082


In [31]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 58,   5,   2],
       [ 28, 109,  37],
       [ 52,  89,  50]])

# ADASYN

In [32]:
from imblearn.over_sampling import ADASYN
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [33]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = ADASYN().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=35)

In [34]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: EMCI


In [35]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.3464249748237664
F1 Score: 0.37186013821050745


In [36]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 94,   7,   4,  11,   1,  42],
       [ 15,  43,  14,   9,  11,  58],
       [ 37,  31,  33,   4,   4,  55],
       [ 26,  10,   3,  34,  10,  75],
       [ 28,  18,  24,  10,  21,  73],
       [ 23,  11,  22,   6,   7, 119]])

### Combined MCI groups

In [37]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [38]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = ADASYN().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=43)

In [39]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: AD


In [40]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.5347985347985348
F1 Score: 0.5659469960485128


In [41]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[150,  44,   3],
       [ 48, 106,  19],
       [ 61,  79,  36]])

# Random Oversampling

In [42]:
from imblearn.over_sampling import RandomOverSampler
oversample = RandomOverSampler(sampling_strategy='minority')
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [43]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=78)

In [44]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: LMCI
Predicted Value: AD


In [45]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.2894736842105263
F1 Score: 0.2851707998721773


In [46]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[90,  0,  0, 19, 10, 40],
       [23, 12, 16, 38, 12, 58],
       [10,  5,  8,  7,  1, 12],
       [ 6,  1,  0,  7,  0, 11],
       [11,  4,  9,  8,  2, 17],
       [ 2,  0,  1,  3,  0, 13]])