# Random Under-sampling

In [1]:
from imblearn.under_sampling import RandomUnderSampler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()
df

AD_MCP    AD_PCT    AD_GCC    AD_BCC    AD_SCC     AD_FX  AD_CST_R  \
0    0.001177  0.000974  0.001479  0.001474  0.001575  0.002257  0.001079   
2    0.001213  0.001075  0.001567  0.001585  0.001686  0.002492  0.001046   
3    0.001101  0.000965  0.001440  0.001433  0.001456  0.002379  0.000985   
4    0.001053  0.000904  0.001433  0.001470  0.001450  0.002421  0.000966   
5    0.001131  0.000974  0.001469  0.001498  0.001531  0.002291  0.000994   
..        ...       ...       ...       ...       ...       ...       ...   
963  0.001117  0.001011  0.001574  0.001646  0.001712  0.002214  0.001094   
964  0.001181  0.001002  0.001423  0.001505  0.001530  0.002266  0.001088   
965  0.001126  0.000949  0.001542  0.001747  0.001642  0.002565  0.000978   
966  0.001090  0.000976  0.001354  0.001421  0.001427  0.001928  0.001018   
967  0.001097  0.000984  0.001477  0.001419  0.001502  0.002556  0.001063   

     AD_CST_L   AD_ML_R   AD_ML_L  ...   RD_FXST    RD_SLF    RD_SFO  \
0    0.001081  0.001285  0.001287  ...  0.000662  0.000577  0.000551   
2    0.001056  0.001149  0.001126  ...  0.000769  0.000694  0.000902   
3    0.000990  0.001118  0.001113  ...  0.000614  0.000546  0.000562   
4    0.000977  0.001047  0.001041  ...  0.000607  0.000535  0.000551   
5    0.001017  0.001128  0.001105  ...  0.000621  0.000559  0.000586   
..        ...       ...       ...  ...       ...       ...       ...   
963  0.001118  0.001228  0.001248  ...  0.000734  0.000647  0.000913   
964  0.001103  0.001224  0.001203  ...  0.000584  0.000593  0.000624   
965  0.001052  0.001162  0.001190  ...  0.000577  0.000589  0.000835   
966  0.001007  0.001241  0.001188  ...  0.000560  0.000517  0.000514   
967  0.001147  0.001268  0.001199  ...  0.000601  0.000537  0.000766   

       RD_UNC    RD_TAP     RD_IC     RD_CC     RD_CR  RD_FULLWM  \
0    0.000600  0.001139  0.000491  0.000562  0.000638   0.000571   
2    0.000717  0.001507  0.000626  0.000701  0.000851   0.000723   
3    0.000553  0.000950  0.000448  0.000512  0.000587   0.000531   
4    0.000530  0.000862  0.000437  0.000509  0.000573   0.000522   
5    0.000558  0.000901  0.000458  0.000527  0.000605   0.000545   
..        ...       ...       ...       ...       ...        ...   
963  0.000599  0.001623  0.000538  0.000680  0.000744   0.000652   
964  0.000619  0.000878  0.000487  0.000567  0.000618   0.000571   
965  0.000534  0.001478  0.000440  0.000694  0.000659   0.000597   
966  0.000566  0.000729  0.000441  0.000469  0.000534   0.000509   
967  0.000605  0.001115  0.000446  0.000598  0.000608   0.000556   

     Research Group  
0                CN  
2                CN  
3                CN  
4                CN  
5                CN  
..              ...  
963              AD  
964              CN  
965              AD  
966              CN  
967             MCI  

[933 rows x 293 columns]

In [2]:
undersample = RandomUnderSampler(sampling_strategy='not minority')

In [3]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=13)

In [5]:
from sklearn.naive_bayes import GaussianNB

# Build a Gaussian Classifier
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: EMCI
Predicted Value: CN


In [6]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
)

y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.16981132075471697
F1 Score: 0.1816185902923567


### Combined MCI groups

In [7]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [8]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=14)

In [9]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: AD


In [10]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.4074074074074074
F1 Score: 0.42193083352503646


In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[6, 3, 1],
       [5, 4, 2],
       [2, 3, 1]])

# Near Miss

## Version 1

In [12]:
from imblearn.under_sampling import NearMiss
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [13]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=1).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=17)

In [14]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: EMCI


In [15]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.20754716981132076
F1 Score: 0.19610661874812818


In [16]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2, 0, 4, 0, 0, 1],
       [0, 3, 3, 0, 3, 0],
       [0, 3, 2, 4, 2, 0],
       [0, 0, 6, 2, 1, 4],
       [0, 2, 4, 0, 0, 2],
       [0, 1, 0, 1, 1, 2]])

### Combined MCI groups

In [17]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [18]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=1).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=19)

In [19]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: MCI


In [20]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.4444444444444444
F1 Score: 0.43106995884773663


In [21]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[5, 3, 3],
       [0, 3, 3],
       [2, 4, 4]])

## Version 2

In [22]:
from imblearn.under_sampling import NearMiss
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [23]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=2).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=17)

In [24]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: EMCI


In [25]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.33962264150943394
F1 Score: 0.36762753319357094


In [26]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 0, 6, 1, 0, 0],
       [0, 3, 1, 3, 1, 1],
       [1, 1, 6, 1, 2, 0],
       [1, 1, 3, 7, 0, 1],
       [2, 2, 3, 0, 0, 1],
       [1, 0, 0, 2, 0, 2]])

### Combined MCI groups

In [27]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [28]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=2).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=19)

In [29]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: MCI


In [30]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.48148148148148145
F1 Score: 0.44587139599179504


In [31]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[7, 4, 0],
       [0, 2, 4],
       [1, 5, 4]])

## Version 3

In [32]:
from imblearn.under_sampling import NearMiss
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [33]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=3).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=17)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/imblearn/under_sampling/_prototype_selection/_nearmiss.py:203: UserWarning: The number of the samples to be selected is larger than the number of samples available. The balancing ratio cannot be ensure and all samples will be returned.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/imblearn/under_sampling/_prototype_selection/_nearmiss.py:203: UserWarning: The number of the samples to be selected is larger than the number of samples available. The balancing ratio cannot be ensure and all samples will be returned.
  warnings.warn(


In [34]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: SMC


In [35]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.27450980392156865
F1 Score: 0.3200459671047906


In [36]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2, 4, 0, 0, 0, 1],
       [1, 1, 0, 0, 3, 5],
       [2, 3, 0, 1, 3, 4],
       [1, 1, 0, 3, 1, 3],
       [0, 0, 0, 1, 4, 2],
       [0, 0, 0, 0, 1, 4]])

### Combined MCI groups

In [37]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [38]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = NearMiss(sampling_strategy='not minority', version=3).fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=19)

In [39]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: MCI


In [40]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.37037037037037035
F1 Score: 0.3959435626102292


In [41]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[6, 1, 4],
       [3, 0, 3],
       [4, 2, 4]])

# Tomek Links

In [42]:
from imblearn.under_sampling import TomekLinks
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [43]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = TomekLinks().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=23)

In [44]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: MCI


In [45]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.27906976744186046
F1 Score: 0.22132250559907812


In [46]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 1,  2,  0,  1,  0,  3],
       [14, 35, 13,  5,  4, 23],
       [12,  3,  3,  1,  0,  3],
       [ 1,  4,  0,  2,  0,  2],
       [ 7,  8,  1,  2,  5, 10],
       [ 0,  3,  0,  2,  0,  2]])

### Combined MCI groups

In [47]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [48]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = TomekLinks().fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=26)

In [49]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: CN


In [50]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.5170454545454546
F1 Score: 0.501998129909338


In [51]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 2,  2,  1],
       [22, 79, 14],
       [13, 33, 10]])

# Condensed Nearest Neighbor

In [52]:
from imblearn.under_sampling import CondensedNearestNeighbour
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [53]:
undersample = CondensedNearestNeighbour(n_neighbors=1)

In [54]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=38)

In [55]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: MCI


In [56]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.1875
F1 Score: 0.19029944653299916


In [57]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[3, 0, 0, 1, 1, 3],
       [3, 2, 1, 3, 1, 7],
       [7, 1, 1, 2, 2, 3],
       [3, 2, 1, 3, 0, 0],
       [2, 1, 1, 1, 2, 3],
       [1, 2, 0, 0, 0, 1]])

### Combined MCI groups

In [58]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [59]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=43)

In [60]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: MCI


In [61]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.48
F1 Score: 0.5024000000000001


In [62]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 7,  1,  1],
       [ 6, 14,  5],
       [ 3, 10,  3]])

# Edited Nearest Neighbors

In [63]:
from imblearn.under_sampling import EditedNearestNeighbours
undersample = EditedNearestNeighbours(n_neighbors=3)
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [64]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=46)

In [65]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: AD
Predicted Value: AD


In [66]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.84375
F1 Score: 0.8606459330143539


In [67]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 7,  3,  0],
       [ 1, 20,  0],
       [ 1,  0,  0]])

What happened here? Aren't there supposed to be six rows and columns? My guess is that ENN removed the data points for some of the other labels (lMCI, eMCI, SMC) since they were too similar to other labels

# One-Sided Selection

In [68]:
from imblearn.under_sampling import OneSidedSelection
undersample = OneSidedSelection(n_neighbors=1, n_seeds_S=200)
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [69]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=46)

In [70]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: SMC
Predicted Value: EMCI


In [71]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.25821596244131456
F1 Score: 0.2601197799479558


In [72]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 1,  0,  5,  1,  0,  3],
       [ 5, 16,  7,  1,  3, 16],
       [ 9,  6,  9,  1,  0, 16],
       [ 2,  7,  0,  5,  0, 15],
       [ 2, 10,  7,  2,  5, 14],
       [ 5,  7,  5,  8,  1, 19]])

### Combined MCI groups

In [73]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [74]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=46)

In [75]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: MCI
Predicted Value: CN


In [76]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.4948453608247423
F1 Score: 0.5286774118068078


In [77]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 4,  4,  0],
       [ 4, 33,  4],
       [ 8, 29, 11]])

# Cluster Centroids

In [78]:
from imblearn.under_sampling import ClusterCentroids
undersample = ClusterCentroids()
df = pd.read_csv('DTI_with_group.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [79]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=46)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: Fut

In [80]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: SMC


In [81]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.16981132075471697
F1 Score: 0.19302458547741566


In [82]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1, 3, 3, 0, 2, 3],
       [0, 0, 2, 1, 0, 5],
       [3, 0, 1, 0, 1, 3],
       [0, 2, 1, 1, 0, 5],
       [0, 0, 3, 0, 1, 3],
       [2, 0, 2, 0, 0, 5]])

### Combined MCI groups

In [83]:
df = pd.read_csv('DTI_with_group_comb.csv')
# remove unnecessary columns + confounding
df = df.drop(['IMAGEUID', 'COLPROT', 'RID', 'VISCODE', 
                          'VISCODE2', 'EXAMDATE', 'VERSION', 'MANUFACTURER',
                         'RUNDATE', 'STATUS', 'QC', 'update_stamp', 'Age', 'VOLUMES', 'Sex'], axis=1)
# remove rows with empty values
df = df.dropna()

In [84]:
X = df.iloc[:, df.columns != 'Research Group'].values
y = df.iloc[:, -1].values
X_resampled, y_resampled = undersample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=46)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [85]:
model = GaussianNB()

# Model training
model.fit(X_train, y_train)

# Predict Output
predicted = model.predict([X_test[6]])

print("Actual Value:", y_test[6])
print("Predicted Value:", predicted[0])

Actual Value: CN
Predicted Value: CN


In [86]:
y_pred = model.predict(X_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.4444444444444444
F1 Score: 0.4407701352145797


In [87]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[5, 6, 0],
       [4, 5, 0],
       [1, 4, 2]])